language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U flake8
  - pip install -U isort
  - pip install -U yapf

# command to run tests
script:
  - python manage.py format
  - python manage.py test
env:
  - Flask=0.12.2
